version: '3.8'

services:
    gomment:
        image: matthinc/gomment:devel
        container_name: gomment
        build: .
        ports:
        - 8000:8000
        volumes:
        - ./docker_db:/opt/db
