version: '3.7'

services:
  nginx:
    image: nginx@${NGINX_HASH}
    restart: 'unless-stopped'
    network_mode: 'host'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/static:ro
